const fs = require('fs');
const plPath = 'assets/sophisticatedbackpacks/pl_pl.json';
const pl = JSON.parse(fs.readFileSync(plPath, 'utf8'));

const dict = {
  "itemGroup.sophisticatedbackpacks": "Sophisticated Backpacks",
  "item.sophisticatedbackpacks.survival_infinity_upgrade": "Ulepszenie Nieskończoności Przetrwania",
  "item.sophisticatedbackpacks.chipped.botanist_workbench_upgrade": "Chipped: Ulepszenie Warsztatu Botanika",
  "item.sophisticatedbackpacks.chipped.botanist_workbench_upgrade.tooltip": "Warsztat Botanika (Chipped) w zakładce ulepszeń",
  "item.sophisticatedbackpacks.chipped.glassblower_upgrade": "Chipped: Ulepszenie Warsztatu Dmuchacza Szkła",
  "item.sophisticatedbackpacks.chipped.glassblower_upgrade.tooltip": "Warsztat Dmuchacza Szkła (Chipped) w zakładce ulepszeń",
  "item.sophisticatedbackpacks.chipped.carpenters_table_upgrade": "Chipped: Ulepszenie Warsztatu Stolarza",
  "item.sophisticatedbackpacks.chipped.carpenters_table_upgrade.tooltip": "Warsztat Stolarza (Chipped) w zakładce ulepszeń",
  "item.sophisticatedbackpacks.chipped.mason_table_upgrade": "Chipped: Ulepszenie Stołu Murarza",
  "item.sophisticatedbackpacks.chipped.mason_table_upgrade.tooltip": "Stół Murarza (Chipped) w zakładce ulepszeń",
  "item.sophisticatedbackpacks.chipped.loom_table_upgrade": "Chipped: Ulepszenie Stołu Tkackiego",
  "item.sophisticatedbackpacks.chipped.loom_table_upgrade.tooltip": "Stół Tkacki (Chipped) w zakładce ulepszeń",
  "item.sophisticatedbackpacks.chipped.alchemy_bench_upgrade": "Chipped: Ulepszenie Ławy Alchemicznej",
  "item.sophisticatedbackpacks.chipped.alchemy_bench_upgrade.tooltip": "Ława Alchemiczna (Chipped) w zakładce ulepszeń",
  "item.sophisticatedbackpacks.chipped.tinkering_table_upgrade": "Chipped: Ulepszenie Stołu Majsterkowania",
  "item.sophisticatedbackpacks.chipped.tinkering_table_upgrade.tooltip": "Stół Majsterkowania (Chipped) w zakładce ulepszeń",
  "item.sophisticatedbackpacks.sawmill.sawmill_upgrade": "Ulepszenie Traka",
  "item.sophisticatedbackpacks.sawmill.sawmill_upgrade.tooltip": "Trak w zakładce ulepszeń",
  "key.category.sophisticatedbackpacks.main": "Sophisticated Backpacks",
  "gui.sophisticatedbackpacks.upgrades.inception": "Wnętrze",
  "gui.sophisticatedbackpacks.error.add.everlasting_exists": "Ulepszenie Wieczności już znajduje się w innym slocie ulepszeń",
  "gui.sophisticatedbackpacks.settings.buttons.another_player_can_open.on": "Inny gracz może otworzyć",
  "gui.sophisticatedbackpacks.settings.buttons.another_player_can_open.on.tooltip": "Gdy ten plecak jest noszony i widoczny, inny gracz może go otworzyć, klikając PPM plecy tego gracza",
  "gui.sophisticatedbackpacks.settings.buttons.another_player_can_open.off": "Inny gracz NIE może otworzyć",
  "gui.sophisticatedbackpacks.settings.buttons.another_player_can_open.off.tooltip": "Plecak nie może zostać otwarty przez innego gracza po kliknięciu PPM pleców gracza, nawet jeśli plecak jest tam noszony",
  "commands.sophisticatedbackpacks.list.cloth_color": "Tkanina",
  "commands.sophisticatedbackpacks.list.trim_color": "Ozdoba",
  "commands.sophisticatedbackpacks.give.success": "Wydano plecak graczowi %s",
  "commands.sophisticatedbackpacks.remove_non_player.success": "Usunięto %s nie-graczowych plecaków",
  "chat.sophisticatedbackpacks.backpack_uuid.tooltip": "Kliknij, aby wydać plecak o UUID: %s",
  "commands.sophisticatedbackpacks.template.list.give": "Wydaj Plecak",
  "commands.sophisticatedbackpacks.template.list.give.tooltip": "Kliknij, aby wydać plecak z szablonem: %s",
  "commands.sophisticatedbackpacks.template.list.delete.tooltip": "Kliknij, aby usunąć szablon: %s",
  "commands.sophisticatedbackpacks.template.list.export": "Eksportuj Szablon",
  "commands.sophisticatedbackpacks.template.list.export.tooltip": "Kliknij, aby wyeksportować szablon '%s' do paczki danych",
  "commands.sophisticatedbackpacks.template.backpackempty": "Plecak jest pusty",
  "commands.sophisticatedbackpacks.template.create.alreadyexists": "Szablon '%s' już istnieje",
  "commands.sophisticatedbackpacks.template.create.success": "Szablon '%s' utworzony pomyślnie",
  "commands.sophisticatedbackpacks.template.delete.success": "Szablon '%s' usunięty pomyślnie",
  "commands.sophisticatedbackpacks.template.give.backpack.success": "Wydano plecak graczowi %s",
  "commands.sophisticatedbackpacks.template.give.failure.notemplate": "Szablon '%s' nie istnieje",
  "commands.sophisticatedbackpacks.template.give.failure.notpersistent": "Szablon '%s' nie jest trwały i nie może być użyty z komendą 'template give'",
  "commands.sophisticatedbackpacks.template.export.success": "Wyeksportowano szablon do %s",
  "commands.sophisticatedbackpacks.template.export.failure.notemplate": "Szablon '%s' nie istnieje",
  "commands.sophisticatedbackpacks.template.export.failure.invalid_characters": "Nazwa szablonu zawiera nieprawidłowe znaki: %s",
  "commands.sophisticatedbackpacks.dynamic.templateInUse": "Dynamiczna nazwa szablonu '%s' jest obecnie używana",
  "commands.sophisticatedbackpacks.dynamic.templateNotInUse": "Dynamiczny szablon '%s' nie jest obecnie używany",
  "commands.sophisticatedbackpacks.dynamic.begin.success": "Pomyślnie rozpoczęto dynamiczny szablon '%s'",
  "commands.sophisticatedbackpacks.dynamic.begin.noBaseTemplate": "Szablon '%s', na którym ma bazować ten dynamiczny szablon, nie istnieje",
  "commands.sophisticatedbackpacks.dynamic.add.delayed": "Przedmiot '%2$s' jest oznaczony do dodania do '%1$s' na końcu",
  "commands.sophisticatedbackpacks.dynamic.add.success": "Pomyślnie dodano przedmiot '%2$s' do '%1$s'",
  "commands.sophisticatedbackpacks.dynamic.end.addRemainingItemsFailed": "Nie wszystkie przedmioty mogły zostać dodane: Pozostało %d x %s",
  "commands.sophisticatedbackpacks.dynamic.end.success": "Pomyślnie zakończono dynamiczny szablon '%s'",
  "sophisticatedbackpacks.configuration.common": "Wspólne",
  "sophisticatedbackpacks.configuration.nerfs": "Osłabienia",
  "sophisticatedbackpacks.configuration.entityBackpackAdditions": "Plecaki Mobów",
  "sophisticatedbackpacks.configuration.inceptionUpgrade": "Ulepszenie Wnętrza",
  "sophisticatedbackpacks.configuration.leatherBackpack": "Skórzany Plecak",
  "sophisticatedbackpacks.configuration.netheriteBackpack": "Netherytowy Plecak",
  "sophisticatedbackpacks.configuration.compactingUpgrade": "Ulepszenie Kompresji",
  "sophisticatedbackpacks.configuration.advancedCompactingUpgrade": "Zaawansowane Ulepszenie Kompresji",
  "sophisticatedbackpacks.configuration.depositUpgrade": "Ulepszenie Depozytu",
  "sophisticatedbackpacks.configuration.advancedDepositUpgrade": "Zaawansowane Ulepszenie Depozytu",
  "sophisticatedbackpacks.configuration.feedingUpgrade": "Ulepszenie Karmienia",
  "sophisticatedbackpacks.configuration.advancedFeedingUpgrade": "Zaawansowane Ulepszenie Karmienia",
  "sophisticatedbackpacks.configuration.magnetUpgrade": "Ulepszenie Magnesu",
  "sophisticatedbackpacks.configuration.advancedMagnetUpgrade": "Zaawansowane Ulepszenie Magnesu",
  "sophisticatedbackpacks.configuration.pickupUpgrade": "Ulepszenie Podnoszenia",
  "sophisticatedbackpacks.configuration.advancedPickupUpgrade": "Zaawansowane Ulepszenie Podnoszenia",
  "sophisticatedbackpacks.configuration.refillUpgrade": "Ulepszenie Uzupełniania",
  "sophisticatedbackpacks.configuration.advancedRefillUpgrade": "Zaawansowane Ulepszenie Uzupełniania",
  "sophisticatedbackpacks.configuration.restockUpgrade": "Ulepszenie Zaopatrywania",
  "sophisticatedbackpacks.configuration.advancedRestockUpgrade": "Zaawansowane Ulepszenie Zaopatrywania",
  "sophisticatedbackpacks.configuration.voidUpgrade": "Ulepszenie Pochłaniania",
  "sophisticatedbackpacks.configuration.advancedVoidUpgrade": "Zaawansowane Ulepszenie Pochłaniania",
  "sophisticatedbackpacks.configuration.stackUpgrade": "Ulepszenie Stosów",
  "sophisticatedbackpacks.configuration.smeltingUpgrade": "Ulepszenie Wytapiania",
  "sophisticatedbackpacks.configuration.smokingUpgrade": "Ulepszenie Wędzenia",
  "sophisticatedbackpacks.configuration.blastingUpgrade": "Ulepszenie Wytapiania Hutniczego",
  "sophisticatedbackpacks.configuration.autoSmeltingUpgrade": "Auto-Wytapianie Ulepszenie",
  "sophisticatedbackpacks.configuration.autoSmokingUpgrade": "Auto-Wędzenie Ulepszenie",
  "sophisticatedbackpacks.configuration.autoBlastingUpgrade": "Auto-Wytapianie Hutnicze Ulepszenie",
  "sophisticatedbackpacks.configuration.toolSwapperUpgrade": "Ulepszenie Zmiany Narzędzi",
  "sophisticatedbackpacks.configuration.tankUpgrade": "Ulepszenie Zbiornika",
  "sophisticatedbackpacks.configuration.batteryUpgrade": "Ulepszenie Baterii",
  "sophisticatedbackpacks.configuration.pumpUpgrade": "Ulepszenie Pompy",
  "sophisticatedbackpacks.configuration.xpPumpUpgrade": "Ulepszenie Pompy PD",
  "sophisticatedbackpacks.configuration.advancedJukeboxUpgrade": "Zaawansowane Ulepszenie Szafy Grającej",
  "sophisticatedbackpacks.configuration.alchemyUpgrade": "Ulepszenie Alchemii",
  "sophisticatedbackpacks.configuration.advancedAlchemyUpgrade": "Zaawansowane Ulepszenie Alchemii",
  "sophisticatedbackpacks.configuration.mobCatcherUpgrade": "Ulepszenie Łapacza Mobów",
  "sophisticatedbackpacks.configuration.upgradeSlotCount": "Sloty Ulepszeń",
  "sophisticatedbackpacks.configuration.slotsInRow": "Sloty Na Wiersz",
  "sophisticatedbackpacks.configuration.fuelFilterSlotsInRow": "Sloty Paliwa Na Wiersz",
  "sophisticatedbackpacks.configuration.numberOfSlots": "Sloty Płyt",
  "sophisticatedbackpacks.configuration.fuelEfficiencyMultiplier": "Wydajność Paliwa",
  "sophisticatedbackpacks.configuration.voidAlwaysEnabled": "Zezwól na Bezpośrednie Pochłanianie",
  "sophisticatedbackpacks.configuration.nonStackableItems": "Przedmioty Niestakowalne",
  "sophisticatedbackpacks.configuration.maxInputOutput": "Limit Transferu",
  "sophisticatedbackpacks.configuration.stackMultiplierRatio": "Skalowanie Ulepszeń Stosów",
  "sophisticatedbackpacks.configuration.capacityPerSlotRow": "Pojemność Zbiornika Na Wiersz",
  "sophisticatedbackpacks.configuration.basicMaxSlotCost": "Koszt Podstawowego Maks. Slota",
  "sophisticatedbackpacks.configuration.advancedMaxSlotCost": "Koszt Zaawansowanego Maks. Slota",
  "sophisticatedbackpacks.configuration.animalMultiplier": "Mnożnik Kosztu Slota Zwierząt",
  "sophisticatedbackpacks.configuration.hostileMultiplier": "Mnożnik Kosztu Slota Wrogich Mobów",
  "sophisticatedbackpacks.configuration.entityBlockList": "Zablokowane Typy Encji",
  "sophisticatedbackpacks.configuration.hostileOverrides": "Nadpisania Wrogich Encji",
  "sophisticatedbackpacks.configuration.passiveOverrides": "Nadpisania Pasywnych Encji",
  "sophisticatedbackpacks.configuration.maxXpPointsPerMending": "Maks. PD Na Naprawę",
  "sophisticatedbackpacks.configuration.chance": "Szansa Pojawienia",
  "sophisticatedbackpacks.configuration.addLoot": "Dodaj Łupy",
  "sophisticatedbackpacks.configuration.buffWithPotionEffects": "Wzmocnij Efektami Mikstur",
  "sophisticatedbackpacks.configuration.equipWithArmor": "Wyposaż w Zbroję",
  "sophisticatedbackpacks.configuration.entityLootTableList": "Tabele Łupów Encji",
  "sophisticatedbackpacks.configuration.discBlockList": "Zablokowane Płyty Muzyczne",
  "sophisticatedbackpacks.configuration.playJukebox": "Odtwarzaj Szafę Grającą",
  "sophisticatedbackpacks.configuration.dropToFakePlayers": "Zezwól na Upuszczenia Fałszywym Graczom",
  "sophisticatedbackpacks.configuration.backpackDropChance": "Szansa Upuszczenia",
  "sophisticatedbackpacks.configuration.lootingChanceIncreasePerLevel": "Bonus Graczenia",
  "sophisticatedbackpacks.configuration.leatherWeight": "Waga Skórzanego",
  "sophisticatedbackpacks.configuration.netheriteWeight": "Waga Netherytowego",
  "sophisticatedbackpacks.configuration.minBackpackTierMidDifficulty": "Min. Poziom przy Średniej Trudności",
  "sophisticatedbackpacks.configuration.minBackpackTierHighDifficulty": "Min. Poziom przy Wysokiej Trudności",
  "sophisticatedbackpacks.configuration.localDifficultyEffectsBackpackSpawns": "Użyj Lokalnej Trudności",
  "sophisticatedbackpacks.configuration.tooManyBackpacksSlowness": "Zbyt Wiele Plecaków Spowalnia Graczy",
  "sophisticatedbackpacks.configuration.maxNumberOfBackpacks": "Maks. Liczba Plecaków Przed Osłabieniem",
  "sophisticatedbackpacks.configuration.slownessLevelsPerAdditionalBackpack": "Poziomy Spowolnienia Za Dodatkowy Plecak",
  "sophisticatedbackpacks.configuration.onlyWornBackpackTriggersUpgrades": "Tylko Noszony Plecak Uruchamia Ulepszenia",
  "sophisticatedbackpacks.configuration.nerfEffect": "Efekt Osłabienia",
  "sophisticatedbackpacks.configuration.upgradesUseInventoriesOfBackpacksInBackpack": "Używaj Ekwipunków Zagnieżdżonych Plecaków",
  "sophisticatedbackpacks.configuration.upgradesInContainedBackpacksAreFunctional": "Ulepszenia Zagnieżdżonych Plecaków Działają",
  "sophisticatedbackpacks.configuration.disallowedItems": "Niedozwolone Przedmioty",
  "sophisticatedbackpacks.configuration.maxUpgradesPerStorage": "Limity Ulepszeń",
  "sophisticatedbackpacks.configuration.allowOpeningOtherPlayerBackpacks": "Pozwól Otwierać Plecaki Innych Graczy"
};

let count = 0;
for (const [k, v] of Object.entries(dict)) {
  if (pl[k] !== undefined) { pl[k] = v; count++; }
  else console.log('MISSING:', k);
}
fs.writeFileSync(plPath, JSON.stringify(pl, null, 2));
console.log('Applied:', count);