const fs = require('fs');
const plPath = 'assets/ftbchunks/pl_pl.json';
const pl = JSON.parse(fs.readFileSync(plPath, 'utf8'));

const dict = {
  "ftbchunks": "FTB Chunks",
  "ftbchunks.config.client.waypoints.death_waypoint_autoremove_distance.tooltip": "Jeśli > 0, najbliższy punkt śmierci zostanie automatycznie usunięty, jeśli jest bliżej niż ta odległość od ciebie",
  "ftbchunks.config.client.waypoints.waypoint_focus_distance.tooltip": "Jak blisko punktu nawigacyjnego musi znajdować się celownik gracza, aby wyświetlić jego nazwę?",
  "ftbchunks.config.client.waypoints.waypoint_focus_scale.tooltip": "Jak duże rosną skupione punkty nawigacyjne?",
  "ftbchunks.config.client.advanced.memory.region_release_time.tooltip": "Limit czasu w sekundach do zwolnienia danych regionów 512x512, które nie były ostatnio używane\nMniejsze wartości oznaczają mniejsze zużycie pamięci, ale większy dostęp do dysku, gdy zwolnione regiony są ponownie ładowane\nUstaw na 0, aby wyłączyć zwalnianie danych regionów.",
  "ftbchunks.config.client.advanced.memory.autorelease_on_map_close": "Auto-zwalnianie regionów po zamknięciu mapy",
  "ftbchunks.config.client.advanced.memory.autorelease_on_map_close.tooltip": "Gdy duża mapa jest zamknięta, automatycznie zwolnij dane regionów do tej liczby.\nMniejsze wartości oznaczają mniejsze zużycie pamięci, ale większy dostęp do dysku, gdy zwolnione regiony są ponownie ładowane\nUstaw na 0, aby wyłączyć zwalnianie danych regionów.",
  "ftbchunks.config.client.advanced.memory.max_zoom_constraint": "Ogranicz oddalanie mapy",
  "ftbchunks.config.client.advanced.memory.max_zoom_constraint.tooltip": "Gdy true, maksymalne oddalenie mapy jest ograniczone liczbą zbadanych regionów i ilością dostępnej pamięci.\nJeśli to przeszkadza, ustaw na false.",
  "ftbchunks.config.client.minimap.xyz": "XYZ",
  "ftbchunks.config.client.minimap.font_scale.tooltip": "Zalecane utrzymanie tej wartości jako wielokrotności 0.5",
  "ftbchunks.config.client.minimap.proportional": "Proporcjonalny rozmiar",
  "key.categories.ftbchunks": "FTB Chunks",
  "ftbteamsconfig.ftbchunks": "Właściwości FTB Chunks",
  "ftbteamsconfig.ftbchunks.allow_fake_players.tooltip": "Traktuj WSZYSTKICH fałszywych graczy jako sojuszników drużyny.\nOSTRZEŻENIE: Ustawienie na true może pozwolić wrogim graczom na dostęp do twoich terenów przez dowolnego fałszywego gracza. Ustaw na false, jeśli nie jesteś pewien.",
  "ftbteamsconfig.ftbchunks.allow_named_fake_players": "Sojusznicze Nazwy/ID Fałszywych Graczy",
  "ftbteamsconfig.ftbchunks.allow_named_fake_players.tooltip": "Traktuj tych fałszywych graczy jako sojuszników drużyny.\nOSTRZEŻENIE: Dodanie wpisów tutaj może pozwolić wrogim graczom na dostęp do twoich terenów przez tych fałszywych graczy. Pozostaw puste, jeśli nie jesteś pewien.",
  "ftbteamsconfig.ftbchunks.allow_fake_players_by_id": "Zezwól Fałszywym Graczom po ID Gracza",
  "ftbteamsconfig.ftbchunks.allow_fake_players_by_id.tooltip": "Pozwala fałszywym graczom mającym ID prawdziwego gracza na dostęp do twoich terenów, JEŚLI ten prawdziwy gracz miałby pozwolenie, jako sojusznik lub członek drużyny. Ustaw na true, jeśli nie jesteś pewien.",
  "ftbteamsconfig.ftbchunks.allow_explosions.tooltip": "Czy eksplozje powinny móc niszczyć bloki na zastrzeżonych terenach?",
  "ftbteamsconfig.ftbchunks.allow_pvp": "Zezwól na Walkę PvP",
  "ftbteamsconfig.ftbchunks.allow_mob_griefing": "Zezwól na Niszczenie Przez Moby",
  "ftbteamsconfig.ftbchunks.allow_mob_griefing.tooltip": "Czy moby powinny mieć pozwolenie na niszczenie bloków na zastrzeżonych terenach?\nUwaga: obecnie tylko Endermany; w przyszłości mogą być inne moby\nEksplozje Creeperów są chronione przez opcję „Zezwól na Eksplozje”",
  "ftbteamsconfig.ftbchunks.block_edit_and_interact_mode.tooltip": "Używane, gdy bloki są stawiane, niszczone lub używane",
  "ftbteamsconfig.ftbchunks.block_edit_mode.tooltip": "Używane, gdy bloki są stawiane lub niszczone",
  "ftbteamsconfig.ftbchunks.block_interact_mode.tooltip": "Używane, gdy bloki są klikane PPM, np. otwieranie skrzyni lub przełączanie dźwigni",
  "ftbteamsconfig.ftbchunks.entity_interact_mode.tooltip": "Używane, gdy encje są klikane PPM",
  "ftbteamsconfig.ftbchunks.nonliving_entity_attack_mode.tooltip": "Używane, gdy nieożywione encje (obrazy, ramki na przedmioty itp.) są klikane LPM",
  "ftbteamsconfig.ftbchunks.location_mode": "Widoczność Lokalizacji",
  "ftbteamsconfig.ftbchunks.location_mode.tooltip": "Kontroluje, kto może cię widzieć na mapie lub minimapie (poza normalnym zasięgiem śledzenia wanilii)",
  "ftbteamsconfig.ftbchunks.claim_visibility": "Widoczność Terenów",
  "ftbteamsconfig.ftbchunks.claim_visibility.tooltip": "Kontroluje, kto może widzieć twoje tereny na mapie lub minimapie",
  "ftbchunks.config.server.fake_players.fake_players": "Zezwól Fałszywym Graczom",
  "ftbchunks.config.server.fake_players.fake_players.tooltip": "CHECK: sprawdzaj dostęp fałszywych graczy jak każdego prawdziwego gracza\nDENY: nigdy nie pozwalaj fałszywym graczom\nALLOW: zawsze pozwalaj fałszywym graczom",
  "ftbchunks.config.server.claiming.max_claimed_chunks": "Maks. Liczba Zastrzeżonych Chunków na Gracza",
  "ftbchunks.config.server.claiming.max_claimed_chunks.tooltip": "Ta wartość domyślna może być nadpisana przez węzeł uprawnień FTB Ranks 'ftbchunks.max_claimed`.",
  "ftbchunks.config.server.force_loading.max_force_loaded_chunks": "Maks. Liczba Wymuszenie Ładowanych Chunków na Gracza",
  "ftbchunks.config.server.force_loading.max_force_loaded_chunks.tooltip": "Ta wartość domyślna może być nadpisana przez węzeł uprawnień FTB Ranks 'ftbchunks.max_force_loaded`.",
  "ftbchunks.config.server.force_loading.force_load_mode.tooltip": "NEVER: pozwól na wymuszone ładowanie chunków tylko, jeśli właściciel drużyny ma co najmniej jednego gracza online\nALWAYS: zawsze pozwól na wymuszone ładowanie, nawet jeśli żaden gracz nie jest online\nDEFAULT: pozwól na wymuszone ładowanie, JEŚLI drużyna ma co najmniej jednego gracza z uprawnieniem FTB Ranks 'ftbchunks.chunk_load_offline'",
  "ftbchunks.config.server.disable_protection.tooltip": "Przydatne na prywatnych serwerach, gdzie wszyscy są zaufani, a tereny służą tylko do wymuszonego ładowania",
  "ftbchunks.config.server.pvp_mode.tooltip": "ALWAYS: zezwól na walkę PvP we wszystkich zastrzeżonych chunkach\nNEVER: zablokuj PvP we wszystkich zastrzeżonych chunkach\nPER_TEAM: drużyny mogą zdecydować, czy PvP jest dozwolone na ich terenach, przez właściwość drużyny",
  "ftbchunks.config.server.ally_mode.tooltip": "DEFAULT: status sojuszu FTB Teams jest sprawdzany, aby ustalić, czy gracze są sojusznikami\nFORCED_ALL: wszyscy gracze są zawsze uważani za sojuszników\nFORCED_NONE: żaden gracz nigdy nie jest uważany za sojusznika",
  "ftbchunks.config.server.claiming.claim_dimension_blacklist": "Czarna Lista Wymiarów",
  "ftbchunks.config.server.claiming.claim_dimension_blacklist.tooltip": "Czarna lista ID wymiarów, w których chunki nie mogą być zastrzegane.\nNp. dodaj \"minecraft:the_end\" do tej listy, jeśli chcesz wyłączyć zastrzeganie chunków w Endzie\nSymbole wieloznaczne są dozwolone, np. \"othermod:*\" dopasowuje wszystkie wymiary dodane przez \"othermod\"",
  "ftbchunks.config.server.claiming.claim_dimension_whitelist": "Biała Lista Wymiarów",
  "ftbchunks.config.server.claiming.claim_dimension_whitelist.tooltip": "Biała lista ID wymiarów, w których chunki mogą być zastrzegane. Jeśli nie jest pusta, wymiar *musi* znajdować się na tej liście (i jednocześnie nie na \"Czarnej Liście Wymiarów\".\nTa sama składnia co dla \"Czarnej Listy Wymiarów\"",
  "ftbchunks.config.server.no_wilderness.tooltip": "Jeśli true, chunki muszą być zastrzeżone, zanim będzie można na nich budować",
  "ftbchunks.config.server.no_wilderness_dimensions.tooltip": "Lista ID wymiarów, w których chunki muszą być zastrzeżone przed modyfikowaniem.\nNp. dodaj \"minecraft:the_nether\", aby wymagać zastrzeżenia chunków w Netherze.\nSymbole wieloznaczne są dozwolone, np. \"othermod:*\" dopasowuje wszystkie wymiary dodane przez \"othermod\"",
  "ftbchunks.config.server.claiming.max_idle_days_before_unclaim.tooltip": "Jeśli żaden członek drużyny nie zaloguje się przez tyle dni, tereny drużyny zostaną zwolnione.\nUstawienie na 0 wyłącza automatyczne zwalnianie terenów.",
  "ftbchunks.config.server.force_loading.max_idle_days_before_unforce.tooltip": "Jeśli żaden członek drużyny nie zaloguje się przez tyle dni, wymuszenie ładowane chunki przestaną być wymuszenie ładowane.\nUstawienie na 0 wyłącza automatyczne cofanie wymuszonego ładowania.",
  "ftbchunks.config.server.long_range_tracker_interval.tooltip": "Interwał w tickach do wysyłania aktualizacji do klientów z danymi śledzenia graczy na dużą odległość.\nMniejsze wartości oznaczają częstsze aktualizacje, ale większe obciążenie serwera i ruch sieciowy; bądź ostrożny, zwłaszcza na zatłoczonych serwerach.\nUstawienie na 0 wyłącza śledzenie na dużą odległość.",
  "ftbchunks.config.server.protect_unknown_explosions.tooltip": "Niektóre źródła eksplozji (np. Ghasty) nie mogą być określone w kodzie.\nJeśli to ustawienie jest true, obrażenia od tych eksplozji są blokowane w chronionych chunkach.",
  "ftbchunks.config.server.claiming.hard_team_claim_limit": "Twardy Maks. Limit Terenów Drużyny",
  "ftbchunks.config.server.force_loading.hard_team_force_limit": "Twardy Maks. Limit Wymuszonego Ładowania Drużyny",
  "ftbchunks.config.server.claiming.party_limit_mode.tooltip": "Metoda obliczania limitów terenów i wymuszonego ładowania grupy.\nLARGEST: użyj limitów członka z największymi limitami\nSUM: zsumuj limity wszystkich członków\nOWNER: użyj tylko limitów właściciela grupy\nAVERAGE: użyj średniej limitów wszystkich członków.",
  "ftbchunks.config.server.require_game_stage.tooltip": "Jeśli true, gracze muszą mieć etap gry 'ftbchunks_mapping' (wymagany KubeJS i/lub Gamestages), aby móc otworzyć mapę lub zobaczyć minimapę",
  "ftbchunks.config.server.location_mode_override.tooltip": "Jeśli true, ustawienia \"Widoczność Lokalizacji\" drużyny są ignorowane i wszyscy gracze mogą się widzieć wszędzie na mapie",
  "ftbchunks.config.server.fake_players.max_prevented_log_age.tooltip": "Wiek w dniach do przechowywania logów zablokowanego dostępu fałszywych graczy\nUwaga: funkcja nie w pełni zaimplementowana; zostanie użyta w przyszłości do wyświetlania i kontrolowania dostępu fałszywych graczy do twoich terenów",
  "ftbchunks.fps": "FPS: %d",
  "ftbchunks.config.server.team_prop_defaults": "Domyślne Właściwości Drużyny",
  "ftbchunks.config.server.team_prop_defaults.def_fake_player_ids": "Zezwól Fałszywym Graczom po ID",
  "ftbchunks.config.server.team_prop_defaults.def_named_fake_players": "Nazwani Fałszywi Gracze",
  "ftbchunks.config.server.team_prop_defaults.def_pvp": "Zezwól na Walkę PvP",
  "ftbchunks.config.server.team_prop_defaults.def_mob_griefing": "Zezwól na Niszczenie Przez Moby",
  "ftbchunks.config.server.team_prop_defaults.def_player_visibility": "Widoczność Lokalizacji",
  "ftbchunks.config.server.team_prop_defaults.def_claim_visibility": "Widoczność Terenów",
  "minimap.info.ftbchunks.biome.title": "Biom",
  "minimap.info.ftbchunks.biome.description": "Renderuj Biom",
  "minimap.info.ftbchunks.fps.title": "FPS",
  "minimap.info.ftbchunks.fps.description": "Renderuj FPS",
  "minimap.info.ftbchunks.game_time.title": "Czas Gry",
  "minimap.info.ftbchunks.game_time.description": "Renderuj Czas Gry",
  "minimap.info.ftbchunks.debug.description": "Renderuj Debug",
  "minimap.info.ftbchunks.player_pos.title": "Pozycja Gracza",
  "minimap.info.ftbchunks.player_pos.description": "Renderuj Pozycję Gracza",
  "minimap.info.ftbchunks.real_time.title": "Czas Rzeczywisty",
  "minimap.info.ftbchunks.real_time.description": "Renderuj Czas Rzeczywisty",
  "minimap.info.ftbchunks.zone.title": "Strefa",
  "minimap.info.ftbchunks.zone.description": "Renderuj Strefę"
};

let count = 0;
for (const [k, v] of Object.entries(dict)) {
  if (pl[k] !== undefined) { pl[k] = v; count++; }
  else console.log('MISSING:', k);
}
fs.writeFileSync(plPath, JSON.stringify(pl, null, 2));
console.log('Applied:', count);