const fs = require('fs');
const path = require('path');

const projectPath = 'assets';

const translations = {
  'block.create_stats': {
    'block.create_stats.arc_furnace': 'Piec łukowy elektryczny',
    'block.create_stats.arc_furnace.tooltip': 'Topi dwa ładunki pod łukiem elektrycznym. Najcięższy obciążenie tego moda.',
    'block.create_stats.arc_furnace.tooltip.placement': 'Prąd wchodzi do złącza przewodowego z tyłu, i tylko z tyłu. Otwór i konsola zwracają się do Ciebie po umieszczeniu.',
    'block.create_stats.arc_furnace.tooltip.shift': 'Kran I pobiera 128 FE/t i kończy w podanych tickach przepisu; Kran II pobiera 512 FE/t i kończy w połowie; Kran III pobiera 1152 FE/t i kończy w jednej trzeciej. Jeśli sieć nie utrzyma kranu, łuk gaśnie, a ponowne zapł kosztuje pełną sekundę poboru bez postępu. Praca, która nigdy nie traci łuku, zyskuje bonusową sztabkę na Krane I; ta, która spędzić ponad ćwierć czasu zatrzymana, zostawia żużel.',
    'block.create_stats.arc_furnace.tooltip.usage': 'Kliknij PPM, aby otworzyć: główny wyłącznik, trzy transformatory kranowe, garnek i bufor. Taśmociągi i lejki ładują dwa sloty ładunku i rozładują produkt oraz żużel.',
    'block.create_stats.blank_monitor_bezel': 'Pusta ramka monitora',
    'block.create_stats.blank_monitor_bezel.tooltip': 'Pusta ramka ekranu. Tylko dekoracja, bez encji bloku, nie akceptuje linków wyświetlacza.',
    'block.create_stats.blank_monitor_bezel.tooltip.placement': 'Zamontuj na dowolnej trwałej ścianie',
    'block.create_stats.blank_monitor_bezel.tooltip.shift': 'Pusta ramka do wystroju serwerowni i ścian monitorów. Jeśli wskażesz na nią Link Wyświetlacza, wyświetli "Nie jest celem wyświetlania": to jest oczekiwane, ten blok nie ma danych za sobą.',
    'block.create_stats.blank_monitor_bezel.tooltip.usage': 'Szukasz wyświetlacza ściennego, który naprawdę pokazuje dane? Użyj Panelu Danych E-Ink zamiast tego',
    'block.create_stats.cable_diagnostic_junction': 'Złącze diagnostyczne kabli',
    'block.create_stats.cable_diagnostic_junction.tooltip': 'Złącze z miernikiem: wszystko, co trafia do pudełka, staje się jednym obwodem.',
    'block.create_stats.cable_diagnostic_junction.tooltip.placement': 'Zamontuj na dowolnej trwałej ścianie, a następnie poprowadź kabel do złączy na górze i dole',
    'block.create_stats.cable_diagnostic_junction.tooltip.shift': 'Łączy przebiegi niezależnie od koloru barwnika, więc służy do celowego łączenia dwóch obwodów. Izolator odcina złącze bez kopania kabli, a karta w środku drzwi wymienia wszystkie kody błędów, które ekran może wyświetlić.',
    'block.create_stats.cable_diagnostic_junction.tooltip.usage': 'Kliknij PPM drzwi, aby otworzyć; pociągnij dźwignię po prawej stronie, aby odciąć pudełko.',
    'block.create_stats.ceramic_mug': 'Ceramiczny kubek',
    'block.create_stats.coffee_machine': 'Ekspres do kawy',
    'block.create_stats.coffee_machine.tooltip': 'Dźwigniowy ekspres do espresso, podłączony do prądu zamiast pary.',
    'block.create_stats.coffee_machine.tooltip.placement': 'Podłącz prąd z tyłu i zapewnij miejsce na dźwignię.',
    'block.create_stats.coffee_machine.tooltip.usage': 'Wrzuć ziarna kakaowe do lejka, zablokuj portafilter, postaw kubek na tacce i pociągnij dźwignię.',
    'block.create_stats.conduit_junction_box': 'Złącze przewodów',
    'block.create_stats.eink_panel': 'Panel Danych E-Ink',
    'block.create_stats.eink_panel.tooltip': 'Elektroniczny papier. Wyświetla jedną liczbę z Linku Wyświetlacza i utrzymuje ją po wyłączeniu zasilania.',
    'block.create_stats.eink_panel.tooltip.placement': 'Zamontuj na dowolnej trwałej ścianie; nie wymaga zasilania i nie emituje światła',
    'block.create_stats.eink_panel.tooltip.shift': 'Płaski, nieoświetlony wyświetlacz ścienny do korytarzy i sal sterowania. Odczytuje zwykły tekst Linku Wyświetlacza z dowolnego bloku Create oraz wszystkie ustrukturyzowane metryki z instrumentów tego moda.',
    'block.create_stats.eink_panel.tooltip.usage': 'Wskaż Link Wyświetlacza na panel z dowolnego źródła Create lub Create Stats, a następnie kliknij PPM panel, aby przełączać między metrykami oferowanymi przez to źródło',
    'block.create_stats.enamel_mug': 'Emaliowany kubek',
    'block.create_stats.fe_battery_controller': 'Kontroler baterii FE',
    'block.create_stats.fe_battery_controller.tooltip': 'Zarządza każdym bankiem kondensatorów dołączonym do niego jako jednym wspólnym zasobem.',
    'block.create_stats.fe_battery_controller.tooltip.placement': 'Sześć wbudowanych złączy, bez potrzeby Złącza Zasilania. Trzy chłodne bolce to wejścia A, B i C; trzy miedziane bolce to wyjścia 1, 2 i 3, po jednym obwodzie.',
    'block.create_stats.fe_battery_controller.tooltip.shift': 'Każde wyjście utrzymuje próg naładowania, poniżej którego nie pobiera rezerwy, więc baza odcina od dołu zamiast zawodzić naraz; przeciągnij suwak wyjścia na mierniku, aby ustawić. Gdy rezerwa spada, kontroler zatrzymuje część generacji, aby ją uzupełnić. Dostrajalny w [power.batteryController].',
    'block.create_stats.fe_battery_controller.tooltip.usage': 'Daj każdemu bankowi jego własne wejście zamiast łączyć banki ze sobą: nic nie jest szeregowo, żadne złącze nie jest pojedynczym punktem awarii, a rezerwa staje się jedną liczbą.',
    'block.create_stats.floor_grating': 'Krata podłogowa',
    'block.create_stats.guard_railing': 'Barierka ochronna',
    'block.create_stats.hazard_trim': 'Oznaczenie niebezpieczeństwa',
    'block.create_stats.indoor_cable': 'Kabel wewnętrzny',
    'block.create_stats.indoor_cable.tooltip': 'Cienki jednopikselowy przewód biegnący środkiem swojego bloku zamiast wzdłuż ściany.',
    'block.create_stats.indoor_cable.tooltip.placement': 'Przyczepia się do ściany, którą klikniesz i podąża za nią. Kliknij PPM pustą ręką, aby przenieść go na inną powierzchnię lub na środek bloku.',
    'block.create_stats.indoor_cable.tooltip.shift': 'Dopasowany do lamp, chłodnic i głośników, a nie maszyn. Jego limit dotyczy przebiegu, więc odgałęzienie z pnia nigdy nie ogranicza pnia.',
    'block.create_stats.indoor_cable.tooltip.usage': 'Zasila wszystko, czego dotyka, i wszystko, przez co wiertło go przeprowadza. Barw go, aby oddzielić jeden obwód od drugiego.',
    'block.create_stats.induction_smelter': 'Piec indukcyjny',
    'block.create_stats.induction_smelter.tooltip': 'Topi i wytapia w objętości taśmociągu. Stykające się piece łączą się w jedną maszynę.',
    'block.create_stats.induction_smelter.tooltip.placement': 'Prąd wchodzi do złącza przewodowego z tyłu, i tylko z tyłu. Otwór, tarcza i tłumik zwracają się do Ciebie po umieszczeniu. Cały bank wymaga jednego podłączenia, w dowolnym miejscu.',
    'block.create_stats.induction_smelter.tooltip.shift': 'O 15% szybszy niż piec lub piec hutniczy, który zastępuje, i nie zużywa paliwa. Pobiera 64 FE/t podczas rozgrzewania lub pracy, a 12 FE/t, aby utrzymać temperaturę bez pracy. Zimny start zużywa 38400 FE, aby się rozgrzać, zanim ruszy pierwszy przedmiot, więc krzyże spotykają się po około dwóch minutach czterdziestu sekundach bezczynności: poniżej tego, utrzymanie jest tańsze, a powyżej moduł pozwala sobie ostygnąć. Wydajność podąża za temperaturą, a kanał wytapiania otwiera się dopiero powyżej czterech piątych pełnej.',
    'block.create_stats.induction_smelter.tooltip.usage': 'Kliknij PPM, aby otworzyć: sam tłumik, tłumik, bufor i temperatura. Kliknij dźwignię z przodu, aby ustawić tłumik bez otwierania czegokolwiek. Taśmociągi i lejki działają na cały bank przez dowolny moduł.',
    'block.create_stats.industrial_power_connector': 'Przemysłowe Złącze Zasilania',
    'block.create_stats.industrial_power_connector.tooltip': 'Końcówka przewodu klasy pniowej.',
    'block.create_stats.industrial_power_connector.tooltip.placement': 'Zamontuj jak inne złącza: na generatorze, baterii lub maszynie zasilanej.',
    'block.create_stats.industrial_power_connector.tooltip.shift': 'Trzyma sześć przewodów zamiast czterech, ponieważ wymaga kilku naraz, aby wypełnić własną moc.',
    'block.create_stats.industrial_power_connector.tooltip.usage': 'Jego moc to suma przewodów, więc wypełnienie go wymaga kilku połączeń Kablem Ekranowanym naraz, a nie jednego.',
    'block.create_stats.kinetic_flywheel.goggle.bank': 'Bank %s dzielący obciążenie · %s SU łącznie, %s%% średnio',
    'block.create_stats.kinetic_flywheel.goggle.charge_draw': 'Pobieranie §f%s§r SU z %s dostępnych',
    'block.create_stats.kinetic_flywheel.goggle.charge_full': '~%s do pełna',
    'block.create_stats.kinetic_flywheel.goggle.charge_starved': 'Oczekiwanie na nadmiar, sieć nie ma wolnych',
    'block.create_stats.kinetic_flywheel.goggle.coasting': 'Jazda na bezwładności, ~%s rezerwy zostało',
    'block.create_stats.kinetic_flywheel.goggle.hold_auto': 'Utrzymywanie §f%s§r RPM (Auto, własna prędkość linii)',
    'block.create_stats.kinetic_flywheel.goggle.hold_set': 'Utrzymywanie §f%s§r RPM (ustawione)',
    'block.create_stats.kinetic_flywheel.goggle.mode.assisting': 'Pomoc · sieć ponad pojemnością',
    'block.create_stats.kinetic_flywheel.goggle.mode.depleted': 'Wyczerpany, odzyskiwanie',
    'block.create_stats.kinetic_flywheel.goggle.mode.parked': 'Zaparkowany ręcznie',
    'block.create_stats.kinetic_flywheel.goggle.mode.waiting': 'W gotowości, linia nie ma nadmiaru',
    'block.create_stats.kinetic_flywheel.goggle.rearm': 'Rozbrajanie za %ss, koszt %s%% pojemności',
    'block.create_stats.kinetic_flywheel.goggle.recovering': 'Wymaga §f%s%%§r zanim ponownie będzie']]]
